### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by krobelus** [krobelus/git-branchstack#1]
Is there a better name?

Some related projects like [git ps](https://github.com/uptech/git-ps) are using the terms "patch stack" or "stacked diffs".  They suggest workflow where each **commit** is a reviewable entity.
git-branchless extends that - each **branch** is reviewable. So maybe one of

- `git branch-stack`
- `git bs`
- `git stacked-branches`

Curiously there is another project recently renamed to https://github.com/arxanas/git-branchless
[This comment](https://github.com/arxanas/git-branchless/issues/4#issuecomment-827917811) has some great name suggestions. For example

- `git monobranch`

which I like because our workflow combats fragmentation of Git branches
similar to how a monorepo simplifies development workflows.

**Comment by fdenzer** [comment]
https://github.com/arxanas/git-branchless has the exact same name. This is confusing.

**Comment by arxanas** [comment]
By the way, the link on the README in the related work above points to your Sourcehut repository. If you'd prefer it to link to the Github repository instead, let me know.
